url: https://mvpweek.github.io
baseurl: /agency-jekyll-theme

# Site settings
title: MVP Week
email: thiago@thiagolunardi.net
description: "Criado pelos membros da comunidades técnicas Microsoft MVP do Brasil, o MVP Week foi idealizado durante o momento de pandemia global a fim de fzermos nossa parte e entregarmos por três semanas repletos de conteúdo técnico."

# Team names, titles and social links
people:
- name: Flavio Farias
  pic: 1
  position: MVP Data Platform
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Thiago Lunardi
  pic: 2
  position: MVP Azure
  social:
    - title: twitter
      url: https://twitter.com/thiagolunardi13
    - title: facebook
      url: https://facebook.com/thiagolunardi
    - title: linkedin
      url: https://de.linkedin.com/en/thiagolunardi

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/mvpweek
  - title: facebook
    url: https://facebook.com/mvpweek
  - title: github
    url: http://github.com/mvpweek

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty